// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v2/admin/tenants": {
            "get": {
                "tags": [
                    "admin-tenants"
                ],
                "summary": "테넌트 목록 (관리자)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "페이지",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "페이지당 항목",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "all",
                        "description": "상태 필터 (active, suspended, all)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/admin/tenants/plans": {
            "get": {
                "tags": [
                    "admin-tenants"
                ],
                "summary": "플랜별 리소스 제한 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/admin/tenants/{id}": {
            "get": {
                "tags": [
                    "admin-tenants"
                ],
                "summary": "테넌트 상세 (관리자)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/admin/tenants/{id}/plan": {
            "put": {
                "tags": [
                    "admin-tenants"
                ],
                "summary": "테넌트 플랜 변경 (관리자)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/admin/tenants/{id}/suspend": {
            "post": {
                "tags": [
                    "admin-tenants"
                ],
                "summary": "테넌트 정지 (관리자)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/admin/tenants/{id}/unsuspend": {
            "post": {
                "tags": [
                    "admin-tenants"
                ],
                "summary": "테넌트 정지 해제 (관리자)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/admin/tenants/{id}/usage": {
            "get": {
                "tags": [
                    "admin-tenants"
                ],
                "summary": "테넌트 사용량 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/install/create-admin": {
            "post": {
                "description": "Creates the initial admin account during installation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "install"
                ],
                "summary": "Create admin account",
                "parameters": [
                    {
                        "description": "Admin account details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v2.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.CreateAdminResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v2/install/status": {
            "get": {
                "description": "Returns whether the system is already installed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "install"
                ],
                "summary": "Check installation status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v2/install/test-db": {
            "post": {
                "description": "Tests if the provided database credentials are valid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "install"
                ],
                "summary": "Test database connection",
                "parameters": [
                    {
                        "description": "Database connection details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v2.TestDBRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.TestDBResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v2/marketplace": {
            "get": {
                "tags": [
                    "marketplace"
                ],
                "summary": "마켓플레이스 탐색",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "페이지",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "페이지당 항목",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "카테고리 필터",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "검색 키워드",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/marketplace/developers/me": {
            "get": {
                "tags": [
                    "marketplace-developer"
                ],
                "summary": "내 개발자 프로필",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/marketplace/developers/register": {
            "post": {
                "tags": [
                    "marketplace-developer"
                ],
                "summary": "개발자 등록",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/marketplace/developers/submissions": {
            "get": {
                "tags": [
                    "marketplace-developer"
                ],
                "summary": "내 제출 목록",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "marketplace-developer"
                ],
                "summary": "플러그인 제출",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/marketplace/{name}": {
            "get": {
                "tags": [
                    "marketplace"
                ],
                "summary": "플러그인 상세",
                "parameters": [
                    {
                        "type": "string",
                        "description": "플러그인 이름",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/marketplace/{name}/download": {
            "post": {
                "tags": [
                    "marketplace"
                ],
                "summary": "다운로드 기록",
                "parameters": [
                    {
                        "type": "string",
                        "description": "플러그인 이름",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/marketplace/{name}/reviews": {
            "get": {
                "tags": [
                    "marketplace"
                ],
                "summary": "플러그인 리뷰 목록",
                "parameters": [
                    {
                        "type": "string",
                        "description": "플러그인 이름",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "marketplace"
                ],
                "summary": "리뷰 작성",
                "parameters": [
                    {
                        "type": "string",
                        "description": "플러그인 이름",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/saas/communities": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "saas"
                ],
                "summary": "원클릭 커뮤니티 생성",
                "parameters": [
                    {
                        "description": "생성 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ProvisionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/saas/communities/{id}": {
            "delete": {
                "tags": [
                    "saas"
                ],
                "summary": "커뮤니티 삭제 (비활성화)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/saas/communities/{id}/invoices": {
            "get": {
                "tags": [
                    "saas"
                ],
                "summary": "청구서 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "페이지",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "페이지당 항목",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/saas/communities/{id}/subscription": {
            "get": {
                "tags": [
                    "saas"
                ],
                "summary": "구독 정보 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/saas/communities/{id}/subscription/cancel": {
            "post": {
                "tags": [
                    "saas"
                ],
                "summary": "구독 취소",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/saas/communities/{id}/subscription/plan": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "saas"
                ],
                "summary": "플랜 변경 (업/다운그레이드)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "플랜 변경 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ChangePlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/api/v2/saas/pricing": {
            "get": {
                "tags": [
                    "saas"
                ],
                "summary": "플랜 가격 정보 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.V2Response"
                        }
                    }
                }
            }
        },
        "/ws/notifications": {
            "get": {
                "tags": [
                    "notifications"
                ],
                "summary": "실시간 알림 WebSocket",
                "responses": {}
            }
        }
    },
    "definitions": {
        "common.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/common.ErrorInfo"
                },
                "meta": {
                    "$ref": "#/definitions/common.Meta"
                }
            }
        },
        "common.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "common.Meta": {
            "type": "object",
            "properties": {
                "board_id": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "common.V2Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "common.V2Meta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "common.V2Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/common.V2Error"
                },
                "meta": {
                    "$ref": "#/definitions/common.V2Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.ChangePlanRequest": {
            "type": "object",
            "required": [
                "plan"
            ],
            "properties": {
                "billing_cycle": {
                    "type": "string",
                    "enum": [
                        "monthly",
                        "yearly"
                    ]
                },
                "plan": {
                    "type": "string",
                    "enum": [
                        "free",
                        "pro",
                        "business",
                        "enterprise"
                    ]
                }
            }
        },
        "domain.ProvisionRequest": {
            "type": "object",
            "required": [
                "owner_email",
                "plan",
                "site_name",
                "subdomain"
            ],
            "properties": {
                "owner_email": {
                    "type": "string"
                },
                "plan": {
                    "type": "string",
                    "enum": [
                        "free",
                        "pro",
                        "business",
                        "enterprise"
                    ]
                },
                "site_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "subdomain": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "v2.CreateAdminRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v2.CreateAdminResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "v2.TestDBRequest": {
            "type": "object",
            "required": [
                "database",
                "host",
                "port",
                "user"
            ],
            "properties": {
                "database": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "v2.TestDBResponse": {
            "type": "object",
            "properties": {
                "hasExistingData": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8082",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "Angple Backend API",
	Description:      "Angple Community Platform - Open Source Backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
